# scp zip-file
- name: unarchive
  unarchive:
    dest: /root
    src: files/awscli-bundle.zip
#    creates: /root/.aws/awscli-bundle
    copy: yes

# install awscli
- name: install
  shell: cd /root && ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws

# create .aws
- name: create /root/.aws
  file: path=/root/.aws state=directory

# use configuration
- name: config
  template: src=files/config dest=/root/.aws/config 
- name: credentials
  template: src=files/credentials dest=/root/.aws/credentials

